print("hello".capitalize())
print("hello".upper())
print("HEllo".lower())
print("hello".startswith("h"))
print("hello".endswith("h"))
print("hello".strip("h"))
print("cashewnut".replace('cashew','coco'))
print("hello i love u".split())
text=" hello i love u. i will always chose uu"
print(text.split('.'))
print(text.count('l'))